### ISSUE TITLE
Warnings in `service.cc`

### ISSUE THREAD

**Issue by achirkin** [mtfranzen/qua-vis-services#1]
Compiling `service.cc` gives some warning including very strange

```
/home/achirkin/Documents/qua-vis-services/src/service.cc:62:23: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
     if (callId = 13371) {
```

Did you mix it with (callId == 13371), or it was intended behavior? :)

**Comment by mtfranzen** [comment]
Yep, I mixed it up. Thanks :)

**Comment by achirkin** [comment]
Though I don't understand why do you have 13371 hardcoded there anyway :)

**Comment by mtfranzen** [comment]
The whole service class is very preliminary and for testing purposes stripped down to basic functionality. That's also why issue #2 is not fixed yet. As soon as we have confirmation that the service works like this, I will extend and refactor it
